apiVersion: apps/v1
kind: Deployment
metadata:
  name: attacker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attacker
  template:
    metadata:
      labels:
        app: attacker
    spec:
      containers:
      - name: attacker
        image: bajacloud/attacker:latest
        ports:
        - containerPort: 80  


---

apiVersion: v1
kind: Service
metadata:
  name: attacker-service
spec:
  selector:
    app: attacker
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 80  
  type: ClusterIP  
